Repository openthread/ot-nrf528xx, pull requests merged in 2021-05, with the labels that each got.

#44 [radio] sync updates from openthread/openthread
  src/nrf52811/openthread-core-nrf52811-config.h
  src/nrf52833/openthread-core-nrf52833-config.h
  src/nrf52840/openthread-core-nrf52840-config.h
  src/src/radio.c
Labels: cla: yes, enhancement

#51 [uart] implement otPlatUartFlush()
  src/src/transport/uart.c
Labels: cla: yes

#56 [build] remove default options
  script/build
Labels: cla: yes

#61 [docs] add step to initialize git submodule
  src/nrf52811/README.md
  src/nrf52833/README.md
  src/nrf52840/README.md
Labels: cla: yes, documentation
