Repository openthread/ot-nrf528xx, pull requests merged in 2021-06, with the labels that each got.

#82 [docs] rename `master ` to `network`
  src/nrf52811/README.md
  src/nrf52833/README.md
  src/nrf52840/README.md
Labels: cla: yes, documentation

#80 [uart] fix uart api for ot cli uart app
  src/src/transport/uart.c
Labels: bug, cla: yes

#75 [link-metrics] split OPENTHREAD_CONFIG_MLE_LINK_METRICS_ENABLE macro
  src/src/radio.c
Labels: cla: yes

#90 [radio] remove use of OT core internal definitions/headers
  src/src/radio.c
Labels: cla: yes, enhancement
